// packages/grapys-vue/src/views/GraphRunner.vue
<template>
  <div class="pointer-events-auto flex max-h-[calc(100vh-90px)] w-100 flex-col">
    <!-- header -->
    <div class="flex cursor-pointer items-center justify-between rounded-t-lg border border-gray-300 bg-gray-100 p-3">
      <div class="flex items-center font-bold">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
          <path
            stroke-linecap="round"
            stroke-linejoin="round"
            d="M7.5 8.25h9m-9 3H12m-9.75 1.51c0 1.6 1.123 2.994 2.707 3.227 1.129.166 2.27.293 3.423.379.35.026.67.21.865.501L12 21l2.755-4.133a1.14 1.14 0 0 1 .865-.501 48.172 48.172 0 0 0 3.423-.379c1.584-.233 2.707-1.626 2.707-3.228V6.741c0-1.602-1.123-2.995-2.707-3.228A48.394 48.394 0 0 0 12 3c-2.392 0-4.744.175-7.043.513C3.373 3.746 2.25 5.14 2.25 6.741v6.018Z"
          />
        </svg>
        <span>Chat</span>
        <span v-if="messages.length > 0" class="ml-2 rounded-full bg-blue-500 px-2 py-1 text-xs text-white">
          {{ messages.length }}
        </span>
      </div>
      <div class="flex items-center space-x-2">
        <button
          @click.stop="run"
          class="rounded-md px-3 py-1 font-medium text-white"
          :class="isRunning || !ready ? 'cursor-not-allowed bg-gray-400' : 'bg-green-500 hover:bg-green-600'"
          :disabled="isRunning || !ready"
        >
          {{ ready ? "Run" : "Loading..." }}
        </button>
        <button
          @click.stop="abort"
          class="rounded-md px-3 py-1 font-medium text-white"
          :class="!isRunning ? 'cursor-not-allowed bg-gray-400' : 'bg-red-500 hover:bg-red-600'"
          :disabled="!isRunning"
        >
          Stop
        </button>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6" @click="onClickClose">
          <path stroke-linecap="round" stroke-linejoin="round" d="M6 18 18 6M6 6l12 12" />
        </svg>
      </div>
    </div>

    <!-- content -->
    <div class="overflow-hidden border border-gray-300 bg-white shadow-lg transition-all duration-300 ease-in-out">
      <div class="flex h-[calc(100vh-160px)] flex-col">
        <!-- message area -->
        <div ref="chatContainerRef" class="flex-1 space-y-2 overflow-y-auto p-6" style="scroll-behavior: smooth">
          <!-- loading -->
          <div v-if="!ready" class="flex h-full flex-col items-center justify-center text-gray-500">
            <div class="mb-2 animate-pulse">Loading...</div>
            <div class="text-sm">{{ loading }}</div>
          </div>

          <!-- ready and no messages -->
          <div v-else-if="ready && messages.length === 0 && !isRunning" class="flex h-full flex-col items-center justify-center text-gray-500">
            <div class="text-center">
              <div class="mb-2 text-lg">Chat is ready</div>
              <div class="text-sm">Click the "Run" button to start the conversation</div>
            </div>
          </div>

          <!-- messages -->
          <chat v-else :messages="messages" :is-streaming="isStreaming" :stream-data="streamData" :stream-node-ids="streamNodes" />
        </div>

        <!-- input area -->
        <div class="border-t border-gray-300 bg-gray-50 p-3">
          <div class="flex items-center">
            <input
              v-model="userInput"
              @keypress="handleKeyPress"
              :placeholder="events.length > 0 ? 'Enter your message...' : 'Chat is ready'"
              class="flex-1 rounded-l-lg border border-gray-300 p-3 focus:ring-2 focus:ring-blue-500 focus:outline-none"
              :disabled="events.length === 0"
            />
            <button
              class="rounded-r-lg px-4 py-3 font-medium text-white"
              :class="events.length === 0 ? 'cursor-not-allowed bg-gray-300' : 'bg-blue-500 hover:bg-blue-600'"
              @click="events.length > 0 && submitText(events[0])"
            >
              <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                <path
                  fill-rule="evenodd"
                  d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-8.707l-3-3a1 1 0 00-1.414 0l-3 3a1 1 0 001.414 1.414L9 9.414V13a1 1 0 102 0V9.414l1.293 1.293a1 1 0 001.414-1.414z"
                  clip-rule="evenodd"
                />
              </svg>
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref, computed, watch, PropType } from "vue";
import { GraphAI, GraphData, AgentFilterInfo, NodeState } from "graphai";

import { useStore } from "../store";

import { useStreamData } from "../utils/vue-plugin/stream";
import { useChatPlugin } from "../utils/vue-plugin/chat";
import { useGraphAIResult } from "../utils/vue-plugin/result";

import Chat from "../components/Chat.vue";

import * as agents from "@graphai/vanilla";
import { openAIAgent, openAIImageAgent } from "@graphai/openai_agent";
import { geminiAgent } from "@graphai/gemini_agent";
import { anthropicAgent } from "@graphai/anthropic_agent";
import { browserlessAgent } from "@graphai/browserless_agent";

import tinyswallowAgent, { modelLoad, loadEngine, CallbackReport } from "../agents/tinyswallow";
import codeRunnerAgent from "../agents/code_runner";
import { textInputEvent } from "../agents/event";

import { getGraphConfigs } from "../graph";
//import { buildFirebaseStreamFilter } from "./firebase";
import { buildFirebaseStreamFilter } from "@receptron/firebase-tools";
import { firebaseApp } from "../utils/firebase/firebase";
import { enableOnCall } from "../config/project";

export default defineComponent({
  components: {
    Chat,
  },
  props: {
    graphData: {
      type: Object as PropType<GraphData>,
      required: true,
    },
  },
  emits: ["close"],
  setup(props, { emit }) {
    const isRunning = ref(false);
    const chatContainerRef = ref<HTMLElement | null>(null);
    const store = useStore();

    const { eventAgent, userInput, events, submitText, clearEvents } = textInputEvent();
    const { messages, chatMessagePlugin } = useChatPlugin();
    const { streamData, streamAgentFilter, streamPlugin, isStreaming } = useStreamData();
    const { graphAIResultPlugin } = useGraphAIResult();

    const { firebaseStreamFilter } = buildFirebaseStreamFilter(firebaseApp, "asia-northeast1", "agent");

    const agentFilters: AgentFilterInfo[] = [
      {
        name: "streamAgentFilter",
        agent: streamAgentFilter,
      },
    ];

    if (enableOnCall) {
      agentFilters.push({
        name: "firebaseStreamFilter",
        agent: firebaseStreamFilter,
        agentIds: ["openAIAgent"],
      });
    }

    let graphai: GraphAI | null = null;
    const run = async () => {
      isRunning.value = true;
      const graphDataWithMeta = {
        ...props.graphData,
        metadata: { ...(props.graphData.metadata ?? {}), data: store.currentData },
      };

      // console.log(getGraphConfigs());
      graphai = new GraphAI(
        graphDataWithMeta,
        {
          ...agents,
          openAIAgent,
          openAIImageAgent,
          anthropicAgent,
          geminiAgent,
          eventAgent,
          tinyswallowAgent,
          browserlessAgent,
          codeRunnerAgent,
        },
        {
          agentFilters,
          config: getGraphConfigs(),
        },
      );
      graphai.registerCallback(streamPlugin(store.streamNodes));
      graphai.registerCallback(chatMessagePlugin(store.resultNodes));
      graphai.registerCallback(graphAIResultPlugin(store.setResult));
      graphai.onLogCallback = ({ nodeId, state, inputs, result, errorMessage }) => {
        if (state === NodeState.Failed) {
          messages.value.push({ role: "error", content: errorMessage ?? "", nodeId });
        }
        console.log({ nodeId, state, inputs, result, errorMessage });
      };

      try {
        await graphai.run();
      } catch (error) {
        console.log(error);
      } finally {
        isRunning.value = false;
      }
    };

    const abort = () => {
      try {
        if (isRunning.value && graphai) {
          graphai.abort();
          clearEvents();
          graphai = null;
        }
      } catch (error) {
        console.log(error);
      } finally {
        isRunning.value = false;
      }
    };

    const streamNodes = computed(() => {
      return store.streamNodes;
    });

    const loading = ref("");
    const ready = ref(false);

    loadEngine();

    modelLoad((report: CallbackReport) => {
      if (report.progress === 1) {
        ready.value = true;
      }
      loading.value = report.text;
      console.log(report.text);
    });

    // Automatically scroll when a message is updated
    watch(
      [messages, streamData],
      () => {
        if (chatContainerRef.value) {
          chatContainerRef.value.scrollTop = chatContainerRef.value.scrollHeight;
        }
      },
      { deep: true },
    );

    // Send message with Enter key
    const handleKeyPress = (event: KeyboardEvent) => {
      if (event.key === "Enter" && events.value.length > 0) {
        submitText(events.value[0]);
      }
    };

    const onClickClose = () => {
      emit("close");
    };

    return {
      run,
      abort,
      isRunning,
      chatContainerRef,

      streamData,
      isStreaming,

      submitText,
      userInput,
      messages,
      events,
      streamNodes,
      handleKeyPress,
      onClickClose,
      loading,
      ready,
    };
  },
});
</script>

// packages/grapys-react/src/views/GraphRunner.tsx
import React, { useState, useEffect, useCallback, useRef } from "react";
import { GraphAI, GraphData } from "graphai";
import * as agents from "@graphai/vanilla";
import { openAIAgent } from "@graphai/openai_agent";
import { geminiAgent } from "@graphai/gemini_agent";
import { anthropicAgent } from "@graphai/anthropic_agent";
import { browserlessAgent } from "@graphai/browserless_agent";

import tinyswallowAgent, { modelLoad, loadEngine, CallbackReport } from "../agents/tinyswallow";
import codeRunnerAgent from "../agents/code_runner";
import { useTextInputEvent } from "../agents/event_react";
import { useLocalStore } from "../store";
import { useStreamData } from "../utils/react-plugin/stream";
import { useChatPlugin } from "../utils/react-plugin/chat";

import { getGraphConfigs } from "../graph";
import { GUIMessage } from "../utils/gui/type";

const GraphRunner: React.FC<{ graphData: GraphData }> = ({ graphData }) => {
  const [isRunning, setIsRunning] = useState(false);
  const streamNodes = useLocalStore((state) => state.streamNodes);
  const resultNodes = useLocalStore((state) => state.resultNodes);
  const currentData = useLocalStore((state) => state.currentData);
  const chatContainerRef = useRef<HTMLDivElement>(null);
  // チャットUIの開閉状態を管理
  const [isChatOpen, setIsChatOpen] = useState(false);

  useEffect(() => {
    loadEngine();
  }, []);

  const { eventAgent, userInput, setUserInput, events, submitText } = useTextInputEvent();
  const { messages, chatMessagePlugin } = useChatPlugin();
  const { streamData, streamAgentFilter, streamPlugin, isStreaming } = useStreamData();

  const agentFilters = [
    {
      name: "streamAgentFilter",
      agent: streamAgentFilter,
    },
  ];

  const [loading, setLoading] = useState("");
  const [ready, setReady] = useState(false);

  useEffect(() => {
    modelLoad((report: CallbackReport) => {
      if (report.progress === 1) {
        setReady(true);
      }
      setLoading(report.text);
      console.log(report.text);
    });
  }, []);

  // Scroll to bottom when messages change
  useEffect(() => {
    if (chatContainerRef.current) {
      chatContainerRef.current.scrollTop = chatContainerRef.current.scrollHeight;
    }
  }, [messages, streamData]);

  const [graphai, setGraphai] = useState<GraphAI | null>(null);
  const run = useCallback(async () => {
    setIsRunning(true);
    // チャットを開始したら自動的にUIを開く
    setIsChatOpen(true);
    const graphDataWithMeta = { ...graphData, metadata: { ...(graphData.metadata ?? {}), data: currentData } };

    const graph = new GraphAI(
      graphDataWithMeta,
      {
        ...agents,
        openAIAgent,
        anthropicAgent,
        geminiAgent,
        eventAgent,
        tinyswallowAgent,
        browserlessAgent,
        codeRunnerAgent,
      },
      {
        agentFilters,
        config: getGraphConfigs(),
      },
    );
    graph.registerCallback(streamPlugin(streamNodes()));
    graph.registerCallback(chatMessagePlugin(resultNodes()));
    setGraphai(graph);
    try {
      await graph.run();
      setIsRunning(false);
    } catch (error) {
      console.log(error);
    }
  }, [eventAgent, streamPlugin, chatMessagePlugin, graphData, streamNodes, currentData, resultNodes]);

  const abort = useCallback(() => {
    try {
      if (isRunning && graphai) {
        graphai.abort();
        setGraphai(null);
      }
    } catch (error) {
      console.log(error);
    } finally {
      setIsRunning(false);
    }
  }, [graphai, isRunning]);

  const handleKeyPress = (e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === "Enter" && events.length > 0) {
      submitText(events[0]);
    }
  };

  const renderChatMessages = () => {
    const streamNodeIds = streamNodes();
    return (
      <>
        {messages.map((m: GUIMessage, k: number) => (
          <div key={k} className={`mb-4 ${m.role === "user" ? "text-right" : "text-left"}`}>
            <div className={`inline-block max-w-[80%] rounded-lg px-4 py-2 ${m.role === "user" ? "bg-blue-500 text-white" : "bg-gray-200 text-gray-800"}`}>
              <div className="mb-1 text-sm font-semibold">{m.role === "user" ? "You" : `AI (${m.nodeId})`}</div>
              <div className="break-words whitespace-pre-wrap">{m.content}</div>
            </div>
          </div>
        ))}
        {streamNodeIds.map((nodeId, k) => (
          <div key={`stream-${k}`} className="mb-4 text-left">
            {isStreaming[nodeId] && (
              <div className="inline-block max-w-[80%] rounded-lg bg-gray-200 px-4 py-2 text-gray-800">
                <div className="mb-1 text-sm font-semibold">AI ({nodeId})</div>
                <div className="break-words whitespace-pre-wrap">{streamData[nodeId]}</div>
              </div>
            )}
          </div>
        ))}
      </>
    );
  };

  return (
    <div className="pointer-events-auto flex w-100 flex-col">
      {/* Chat header */}
      <div
        className="flex cursor-pointer items-center justify-between rounded-t-lg border border-gray-300 bg-gray-100 p-3"
        onClick={() => setIsChatOpen(!isChatOpen)}
      >
        <div className="flex items-center font-bold">
          <span>Chat</span>
          {messages.length > 0 && <span className="ml-2 rounded-full bg-blue-500 px-2 py-1 text-xs text-white">{messages.length}</span>}
        </div>
        <div className="flex items-center space-x-2">
          <button
            onClick={(e) => {
              e.stopPropagation();
              run();
            }}
            className={`rounded-md px-3 py-1 font-medium text-white ${isRunning ? "cursor-not-allowed bg-gray-400" : "bg-green-500 hover:bg-green-600"}`}
            disabled={isRunning}
          >
            {ready ? "Run" : "Loading..."}
          </button>
          <button
            onClick={(e) => {
              e.stopPropagation();
              abort();
            }}
            className={`rounded-md px-3 py-1 font-medium text-white ${!isRunning ? "cursor-not-allowed bg-gray-400" : "bg-red-500 hover:bg-red-600"}`}
            disabled={!isRunning}
          >
            Stop
          </button>
          <svg
            xmlns="http://www.w3.org/2000/svg"
            className={`h-5 w-5 transition-transform duration-300 ${isChatOpen ? "rotate-180" : ""}`}
            viewBox="0 0 20 20"
            fill="currentColor"
          >
            <path
              fillRule="evenodd"
              d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z"
              clipRule="evenodd"
            />
          </svg>
        </div>
      </div>

      {/* Chat content */}
      <div
        className={`overflow-hidden border border-gray-300 bg-white shadow-lg transition-all duration-300 ease-in-out ${
          isChatOpen ? "max-h-[calc(100vh-100px)]" : "max-h-0"
        }`}
      >
        <div className="flex h-[calc(100vh-100px)] flex-col">
          {/* Chat messages container */}
          <div ref={chatContainerRef} className="flex-1 space-y-2 overflow-y-auto p-6" style={{ scrollBehavior: "smooth" }}>
            {!ready && (
              <div className="flex h-full flex-col items-center justify-center text-gray-500">
                <div className="mb-2 animate-pulse">Loading...</div>
                <div className="text-sm">{loading}</div>
              </div>
            )}
            {ready && messages.length === 0 && !isRunning && (
              <div className="flex h-full flex-col items-center justify-center text-gray-500">
                <div className="text-center">
                  <div className="mb-2 text-lg">Chat is ready</div>
                  <div className="text-sm">Click the "Run" button to start the conversation</div>
                </div>
              </div>
            )}
            {renderChatMessages()}
          </div>

          {/* Chat input */}
          <div className="border-t border-gray-300 bg-gray-50 p-3">
            <div className="flex items-center">
              <input
                value={userInput}
                onChange={(e) => setUserInput(e.target.value)}
                onKeyPress={handleKeyPress}
                placeholder={events.length > 0 ? "Enter your message..." : "Chat is ready"}
                className="flex-1 rounded-l-lg border border-gray-300 p-3 focus:ring-2 focus:ring-blue-500 focus:outline-none"
                disabled={events.length === 0}
              />
              <button
                className={`rounded-r-lg px-4 py-3 font-medium text-white ${
                  events.length === 0 ? "cursor-not-allowed bg-gray-300" : "bg-blue-500 hover:bg-blue-600"
                }`}
                onClick={() => {
                  if (events.length > 0) {
                    submitText(events[0]);
                  }
                }}
                disabled={events.length === 0}
              >
                <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                  <path
                    fillRule="evenodd"
                    d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-8.707l-3-3a1 1 0 00-1.414 0l-3 3a1 1 0 001.414 1.414L9 9.414V13a1 1 0 102 0V9.414l1.293 1.293a1 1 0 001.414-1.414z"
                    clipRule="evenodd"
                  />
                </svg>
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default GraphRunner;
